// Auto-generated
let project = new Project('jenga_1_0_33');

project.addSources('Sources');
project.addLibrary("../../../../sdk/armsdk/armory");
project.addLibrary("../../../../sdk/armsdk/iron");
project.addLibrary("../../../../sdk/armsdk/lib/haxebullet");
project.addAssets("../../../sdk/armsdk/lib/haxebullet/ammo/ammo.js", { notinlist: true });
project.addParameter('-dce full');
project.addParameter('armory.trait.PhysicsDrag');
project.addParameter("--macro keep('armory.trait.PhysicsDrag')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('jenga.Menu');
project.addParameter("--macro keep('jenga.Menu')");
project.addParameter('jenga.Game');
project.addParameter("--macro keep('jenga.Game')");
project.addShaders("build_jenga/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_jenga/compiled/Assets/**", { notinlist: true });
project.addAssets("build_jenga/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("../../../sdk/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("../../../sdk/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("../../../sdk/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("Bundled/index.html", { notinlist: true });
project.addAssets("Bundled/mono.ttf", { notinlist: false });
project.addAssets("Data/Wood023_1K-JPG/Wood023_1K_Color.jpg", { notinlist: true });
project.addAssets("Data/Wood023_1K-JPG/Wood023_1K_Displacement.jpg", { notinlist: true });
project.addAssets("Data/Wood023_1K-JPG/Wood023_1K_Normal.jpg", { notinlist: true });
project.addAssets("Data/Wood023_1K-JPG/Wood023_1K_Roughness.jpg", { notinlist: true });
project.addAssets("Data/checker_rough.png", { notinlist: true });
project.addAssets("Data/gridbox2.png", { notinlist: true });
project.addAssets("Data/studio_small_05_1k.hdr", { notinlist: true });
project.addLibrary("../../../../sdk/armsdk/lib/zui");
project.addAssets("../../../sdk/armsdk/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=4096');
project.addDefine('rp_shadowmap_cube=2048');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=TAA');
project.addDefine('arm_veloc');
project.addDefine('arm_taa');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=RTAO');
project.addDefine('rp_bloom');
project.addDefine('rp_ssr');
project.addDefine('rp_motionblur=Object');
project.addDefine('rp_gbuffer2');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_published');
project.addDefine('arm_soundcompress');
project.addDefine('arm_audio');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles');
project.addDefine('arm_loadscreen');
project.addDefine('arm_resizable');


resolve(project);
