name: build

on:
  push:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    env:
      armsdk_version: 21.08
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache armsdk
        uses: actions/cache@v2
        env:
          armsdk-cache-version: ${{ env.armsdk_version }}
        with:
          path: _armsdk_
          key: armsdk-cache-${{ env.armsdk-cache-version }}
      - name: Build
        id: publish
        uses: tong/armory_gh_actions@v0.1.5
        with:
          blend: jenga.blend
          publish: web
          blender: latest/candidate
      - name: Result
        run: |
          echo "Code: ${{ steps.publish.outputs.code }}"
          echo "Time: ${{ steps.publish.outputs.time }}"
