name: build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache armsdk
        uses: actions/cache@v2
        env:
          armsdk-cache-version: b0254a1
        with:
          path: ./armsdk
          key: armsdk-cache-${{ env.armsdk-cache-version }}
      - name: Build
        uses: tong/armory_gh_actions@v0.34.0
        with:
          blend: jenga.blend
          exporter: html5
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build_jenga/html5
          target-folder: .
