name: build

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Cache armsdk
      #   uses: actions/cache@v2
      #   env:
      #     armsdk-cache-version: ${{ env.armsdk_version }}
      #   with:
      #     path: _armsdk_
      #     key: armsdk-cache-${{ env.armsdk-cache-version }}
      - name: Build
        id: publish
        uses: tong/armory_gh_actions@v0.1.10
        with:
          publish: web
          blend: jenga.blend
          blender: latest/stable
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build_jenga/html5
          target-folder: web-desktop
