name: deploy-gh-pages

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: publish
        uses: armory3d/armory_gh_actions@v0.1.10
        with:
          publish: web
          blend: jenga.blend
          blender: latest/stable
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build_jenga/html5
