name: build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      armsdk:
        description: Armsdk version/ref to use
        required: false
        default: 21.08
      blender:
        description: Blender version to use (snap)
        required: false
        default: latest/candstableidate
jobs:
  build:
    env:
      armsdk_version: 21.08
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Cache armsdk
      #   uses: actions/cache@v2
      #   env:
      #     armsdk-cache-version: ${{ env.armsdk_version }}
      #   with:
      #     path: _armsdk_
      #     key: armsdk-cache-${{ env.armsdk_version }}
      - name: Build
        id: publish
        uses: tong/armory_gh_actions@v0.1.9
        with:
          publish: web
          armsdk_ref: ${{ env.armsdk_version }}
          blend: jenga.blend
          blender: latest/stable
      - name: Result
        run: |
          echo "Code: ${{ steps.publish.outputs.code }}"
          echo "Time: ${{ steps.publish.outputs.time }}"
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build_jenga/html5
