name: test

on:
  push:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Html5
        id: html5
        uses: armory3d/armory_gh_actions@v0.1.10
        with:
          build: web
          blend: jenga.blend
          blender: latest/stable
      - name: Krom
        id: krom
        uses: armory3d/armory_gh_actions@v0.1.10
        with:
          build: linux-krom
          blend: jenga.blend
          blender: latest/stable
      # - name: Deploy gh-pages
      #   uses: JamesIves/github-pages-deploy-action@4.1.5
      #   with:
      #     branch: gh-pages
      #     folder: build_jenga/html5
