name: test

on:
  push:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Html5
        id: html5
        uses: armory3d/armory_gh_actions@v0.1.10
        with:
          build: html5
          blend: jenga.blend
          blender: latest/stable
      - name: Krom
        id: krom
        uses: armory3d/armory_gh_actions@v0.1.10
        with:
          build: krom-linux
          blend: jenga.blend
          blender: latest/stable
      - name: Linux
        id: linux
        uses: armory3d/armory_gh_actions@v0.1.10
        with:
          build: linux-hl
          blend: jenga.blend
          blender: latest/stable
